/**
 * Generates src/lib/verse-counts.ts with static verse count data per book/chapter.
 * Reads from the SQLite database.
 *
 * Usage: npx tsx scripts/generate-verse-counts.ts
 */

import Database from 'better-sqlite3';
import * as fs from 'fs';
import * as path from 'path';

const DB_PATH = path.join(process.cwd(), 'data', 'bible.db');
const OUTPUT_PATH = path.join(process.cwd(), 'src', 'lib', 'verse-counts.ts');

if (!fs.existsSync(DB_PATH)) {
  console.error('Database not found:', DB_PATH);
  process.exit(1);
}

const db = new Database(DB_PATH, { readonly: true });

// Get all books
const books = db.prepare('SELECT id, chapters FROM books ORDER BY id').all() as { id: number; chapters: number }[];

// Build verse counts: bookId → [verseCountCh1, verseCountCh2, ...]
const verseCounts: Record<number, number[]> = {};

for (const book of books) {
  const counts: number[] = [];
  for (let ch = 1; ch <= book.chapters; ch++) {
    const result = db.prepare(
      'SELECT MAX(verse) as count FROM verses WHERE book_id = ? AND chapter = ? AND bible = ?'
    ).get(book.id, ch, 'osnb2') as { count: number } | undefined;
    counts.push(result?.count ?? 0);
  }
  verseCounts[book.id] = counts;
}

db.close();

// Generate TypeScript file
const entries = Object.entries(verseCounts)
  .map(([id, counts]) => `  ${id}: [${counts.join(', ')}]`)
  .join(',\n');

const output = `// Auto-generated by scripts/generate-verse-counts.ts — do not edit manually
// bookId → [verseCountCh1, verseCountCh2, ...]
export const verseCounts: Record<number, number[]> = {
${entries},
};

export function getChapterVerseCount(bookId: number, chapter: number): number {
  return verseCounts[bookId]?.[chapter - 1] ?? 0;
}
`;

fs.writeFileSync(OUTPUT_PATH, output, 'utf-8');
console.log(`Generated ${OUTPUT_PATH}`);
console.log(`${books.length} books, ${Object.values(verseCounts).reduce((s, c) => s + c.length, 0)} chapters total`);
